# Permalinks
permalink:           pretty

# Setup
title:               Android Tutorials
tagline:             Android Slides
url:                 https://ulat.github.io/HTL-Android-Slides/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bernhard Mayr
  url:               http://github.com/ulat
  email:

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
